#Plugin and Config made by MatzeLP

#Command Settings:

Command: "v"
Description: "§4§lVanishSystem"
Usage: "/v"
Aliase: ["v", "van"]
Permission: "vanish.use"

#Messages

vanish.on: "§3[Paincraft]§6 Du Bist Nun Im §cVanish"
vanish.off:  "§3[Paincraft]§6 Du Bist nicht Mehr Im §cVanish"

