#Plugin and Config made by Crow Balde

#Command Settings:

Command: "v"
Description: "§4VanishSystem"
Usage: "/v"
Aliase: ["v", "van"]
Permission: "vanish.use"

#Messages

vanish.on: "§3[Paincraft]§6 Du Bist Nun Im un Im §c"
vanish.off:  "§3[Paincraft]§6 Du Bist Nicht Mehr Im §cVanish"

